"""add user_id to card and collection

Revision ID: 651667c66d63
Revises: b07af4e08ff1
Create Date: 2026-07-11 22:38:17.130954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '651667c66d63'
down_revision: Union[str, Sequence[str], None] = 'b07af4e08ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_card_user_id'), 'card', ['user_id'], unique=False)
    op.add_column('collection', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('collection_name_key'), 'collection', type_='unique')
    op.create_index(op.f('ix_collection_user_id'), 'collection', ['user_id'], unique=False)
    op.create_unique_constraint('uq_collection_user_id_name', 'collection', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_collection_user_id_name', 'collection', type_='unique')
    op.drop_index(op.f('ix_collection_user_id'), table_name='collection')
    op.create_unique_constraint(op.f('collection_name_key'), 'collection', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('collection', 'user_id')
    op.drop_index(op.f('ix_card_user_id'), table_name='card')
    op.drop_column('card', 'user_id')
    # ### end Alembic commands ###
