"""cascade delete and index for collection_card fks

Revision ID: b07af4e08ff1
Revises: fc2807e5bfd7
Create Date: 2026-07-10 16:49:52.946803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b07af4e08ff1'
down_revision: Union[str, Sequence[str], None] = 'fc2807e5bfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collectioncard_card_id'), 'collectioncard', ['card_id'], unique=False)
    op.drop_constraint(op.f('collectioncard_collection_id_fkey'), 'collectioncard', type_='foreignkey')
    op.drop_constraint(op.f('collectioncard_card_id_fkey'), 'collectioncard', type_='foreignkey')
    op.create_foreign_key(None, 'collectioncard', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collectioncard', 'card', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collectioncard', type_='foreignkey')
    op.drop_constraint(None, 'collectioncard', type_='foreignkey')
    op.create_foreign_key(op.f('collectioncard_card_id_fkey'), 'collectioncard', 'card', ['card_id'], ['id'])
    op.create_foreign_key(op.f('collectioncard_collection_id_fkey'), 'collectioncard', 'collection', ['collection_id'], ['id'])
    op.drop_index(op.f('ix_collectioncard_card_id'), table_name='collectioncard')
    # ### end Alembic commands ###
