"""init cards collections

Revision ID: fc2807e5bfd7
Revises: 
Create Date: 2026-07-10 16:37:47.176381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc2807e5bfd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_base64', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_parsed_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_parsed_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_set_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_set_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_collector_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_scryfall_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matched_data', sa.JSON(), nullable=True),
    sa.Column('enrichment_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('pending','enriched','unrecognized','error')", name='ck_card_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collectioncard',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collectioncard')
    op.drop_table('collection')
    op.drop_table('card')
    # ### end Alembic commands ###
